# Generated by Django 4.0.6 on 2022-09-22 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('initialPrice', models.IntegerField(default=5000)),
                ('closingDate', models.DateField(null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('status', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='userDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('gender', models.BooleanField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('mode', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SoldItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('custId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.userdetails')),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.userdetails'),
        ),
        migrations.CreateModel(
            name='Biddings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidd', models.IntegerField()),
                ('custId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.userdetails')),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.item')),
            ],
        ),
    ]
