# Generated by Django 4.0.6 on 2022-09-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_category_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='closingDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
